jenkins:
  property1:
    sub1: sub-property1
    sub2: sub-property2
    sub3: sub-property3
  property2: property2

environment:
  property1: ${YOUR_PROPERTY_VALUE_1}
  property2: ${YOUR_PROPERTY_VALUE_2}
